version: "latest"

services:
  db:
    container_name: task-management_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - net
  app:
    container_name: task_management_app
    image: dockococo45/task-management:0.0.1-SNAPSHOT
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - net
networks:
  net:
    driver: bridge